apiVersion: v1
appVersion: "v0.1.0"
description: A Helm chart for Kubernetes
name: kube-iptables-tailer
version: 0.2.0
home: https://github.com/geek-cookbook/helm-kube-iptables-tailer
keywords:
- kube-iptables-tailer
- iptables
- calico
- networkpolicy
maintainers:
- email: matthieu.paret@lifen.fr
  name: mtparet
- email: davidy@funkypenguin.co.nz
  name: funkypenguin
sources:
- https://github.com/box/kube-iptables-tailer
